function [fitresult, gof] = createFit_KINGS(V_pr, u_pr)
%CREATEFIT(V_PR,U_PR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V_pr
%      Y Output: u_pr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-May-2017 18:54:50


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V_pr, u_pr );

% Set up fittype and options.
ft = fittype( 'real(sqrt( app+bpp*x^(n)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.239932010568717 0.167927145682257 0.712694471678914];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Kings Law Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Velocity vs Voltage', 'Kings Fit', 'Location', 'NorthEast' );
% Label axes
xlabel V_pr
ylabel u_pr
grid on


