function figure_creator(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-May-2017 15:47:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XMinorTick','on','XScale','log',...
    'FontSize',14,...
    'Position',[0.0550660792951542 0.0808823529411765 0.918502202643172 0.873161764705882]);
box(axes1,'on');
hold(axes1,'on');

semilogx(X1,Y1); % DO PLOT
xlabel('y+','FontSize',14); % Create xlabel
ylabel('u-uinf/utau','FontSize',14); % Create ylabel

% Create title
title('Outer scaled velocity profile (deficit form)','FontSize',16);

